### ISSUE TITLE
Fix documentation grammar

### ISSUE THREAD

**Issue by ch3ber** [ch3ber/yourRouter-docs#1]
Verify that the grammar of all documentation is well written

**Comment by NnajiChimuanya** [comment]
Assign me this task

**Comment by ginn-kazama5656** [comment]
Could you assign me this task?

**Comment by ch3ber** [comment]
@NnajiChimuanya  @vaibhavmishra4g Happy hacking!

**Comment by NnajiChimuanya** [comment]
> Verify that the grammar of all documentation is well written

I've made the changes, but I need access to the repo to create a pull request.

**Comment by ch3ber** [comment]
Create a fork of this project, and make a pull request from your fork

**Comment by NnajiChimuanya** [comment]
okay

**Comment by ch3ber** [comment]
@NnajiChimuanya I have just uploaded the contribution file in case it helps you.

**Comment by NnajiChimuanya** [comment]
Just created the PR
