### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by ch3ber** [ch3ber/yourRouter-docs#2]
Add the documentation from the utilities directory

**Comment by ShivaRapolu01** [comment]
@ch3ber i would like to work on this please assign this to me

**Comment by ShivaRapolu01** [comment]
The documentation is not finished yet

**Comment by ch3ber** [comment]
Sure @ShivaRapolu01

**Comment by ShivaRapolu01** [comment]
@ch3ber can you please say me how you want the documentation to be updated?
